title: One Page Wonder - Jekyll
description: A Jekyll Landing Page Theme
sitename: Digital Infra
baseurl: ''
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME